Power Query

Dynamic Rename from Table

Code:

Rename From table
= Table.RenameColumns(#"Removed Columns3",{{"January 2019", Text.From(Date[YEAR TABLE]{0})},{"February 2019", Text.From(Date[YEAR TABLE]{1})},{"March 2019",
Text.From(Date[YEAR TABLE]{2})},{"April 2019", Text.From(Date[YEAR TABLE]{3})},
{"May 2019", Text.From(Date[YEAR TABLE]{4})},{"June 2019", Text.From(Date[YEAR TABLE]{5})},{"July 2019", Text.From(Date[YEAR TABLE]{6})},
{"August 2019", Text.From(Date[YEAR TABLE]{7})},{"September 2019", Text.From(Date[YEAR TABLE]{8})},{"October 2019", Text.From(Date[YEAR TABLE]{9})},
{"November 2019", Text.From(Date[YEAR TABLE]{10})},{"December 2019", Text.From(Date[YEAR TABLE]{11})},{"January 2020", Text.From(Date[YEAR TABLE]{12})},
{"February 2020", Text.From(Date[YEAR TABLE]{13})},{"March 2020", Text.From(Date[YEAR TABLE]{14})},{"April 2020", Text.From(Date[YEAR TABLE]{15})},
{"May 2020", Text.From(Date[YEAR TABLE]{16})},{"June 2020", Text.From(Date[YEAR TABLE]{17})},{"July 2020", Text.From(Date[YEAR TABLE]{18})},
{"August 2020", Text.From(Date[YEAR TABLE]{19})},{"September 2020", Text.From(Date[YEAR TABLE]{20})},
{"October 2020", Text.From(Date[YEAR TABLE]{21})},{"November 2020", Text.From(Date[YEAR TABLE]{22})},{"December 2020", Text.From(Date[YEAR TABLE]{23})}})

Definition

Allows users to perform a dynamic rename from query table list of values and their indexes.
